name: quill_native_bridge_example
description: "Demonstrates usage of the quill_native_bridge plugin."
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter

  quill_native_bridge:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/