name: quill_native_bridge
description: "An internal plugin for flutter_quill package to access platform-specific APIs"
version: 10.6.5
homepage: https://github.com/singerdmx/flutter-quill/tree/master/quill_native_bridge/
repository: https://github.com/singerdmx/flutter-quill/tree/master/quill_native_bridge/
issue_tracker: https://github.com/singerdmx/flutter-quill/issues/
documentation: https://github.com/singerdmx/flutter-quill/tree/master/quill_native_bridge/

platforms:
  android:
  ios:
  macos:

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

  # For web only
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutterquill.quill_native_bridge
        pluginClass: QuillNativeBridgePlugin
      ios:
        pluginClass: QuillNativeBridgePlugin
      macos:
        pluginClass: QuillNativeBridgePlugin
      web:
        pluginClass: QuillNativeBridgeWeb
        fileName: src/web/quill_native_bridge_web.dart